sudo: false

language: python

cache:
    apt: true

addons:
    apt:
        packages:
            - curl
            - libfcgi0ldbl

notifications:
    webhooks: https://fathomless-fjord-24024.herokuapp.com/notify

services:
  - docker

before_install:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" $DOCKER_REGISTER;

script:
    - bin/build
    - bin/test

after_success:
  - bin/push